name: Build and push a docker container
description: This actions builds a multiarch docker container, and pushes it to docker hub.
author: Netfloex
inputs:
    username:
        required: true
        description: Username of docker hub
    token:
        required: true
        description: Access token or password
    tags:
        required: true
        description: Username Repo and tag, user/repo:tag

runs:
    using: composite
    steps:
        # Setup
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v1.2.0
          with:
              platforms: linux/amd64,linux/arm64,linux/arm/v7

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1.6.0

        # Login
        - name: Login to DockerHub
          uses: docker/login-action@v1.10.0
          with:
              username: ${{ inputs.USERNAME }}
              password: ${{ inputs.TOKEN }}

        # Build & Push
        - name: Build Dockerfile and push
          uses: docker/build-push-action@v2.7.0
          with:
              push: true
              tags: ${{ inputs.tags }}
              platforms: |
                  linux/amd64
                  linux/arm64
                  linux/arm/v7
              # Cache
              cache-from: type=gha
              cache-to: type=gha,mode=max
