name: Checkout and install dependencies
description: This actions installs yarn, and runs yarn install
author: Netfloex
inputs:
    node-version:
        required: false
        description: Node version
        default: 12.22.7

runs:
    using: "composite"
    steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Setup NodeJS
          uses: actions/setup-node@v2
          with:
              node-version: ${{ inputs.node-version }}
              cache: yarn

        - name: Install Dependencies
          run: yarn install --frozen-lockfile --ignore-scripts
